version = 0.1
[default.deploy.parameters]
stack_name = "aws-s3-react-app"
#resolve_s3 = true
s3_prefix = "aws-s3-react-app"
s3_bucket = "aws-s3-react-app-trw"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
